### PR TITLE
Encoding atomic predicates

### PR DESCRIPTION
**Pull request by seanmcl**
Encode p(x1, x2, ...) as first-order to allow for easier metatheory.  When using the atomic predicates in non-trivial ways during constraint reasoning, I was getting spurious coverage errors where the predicate functions (e.g. of LF type i -> i -> typ⁺) could depend on hypotheses.

### CODE REVIEW

**Comment by seanmcl** [comment]
I'll rebase this on the whitespace change to make it easier to see if you like.  Otherwise you can just discard the previous PR.

**Comment by robsimmons** [comment]
So in the version that's there right now (pre-this-pr), you can have quantifiers, but you can't actually use first order terms anywhere, correct?

**Comment by seanmcl** [comment]
You can typecheck terms, e.g. 

  example = (∃ [x] ↓ (∀ [y] P x y)) ⊃ (∀ [x] ↑ (∃ [y] ↓ (P x y))).

but I couldn't get the metatheorems to go through.  So it depends what you mean by "use them".

**Comment by robsimmons** [comment]
Fair enough - this makes sense to include, then, it's minimal extra complexity for monumentally more expressive power.

**Comment by seanmcl** [comment]
The unicode looks better in Emacs than github :|

**Pull request merged**
